// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvCpwb9xetODxrgxxVke8JCIZh7lfQU8',
    appId: '1:82887882958:web:e78e94f551a4c9024d389f',
    messagingSenderId: '82887882958',
    projectId: 'habitspark-6ace3',
    authDomain: 'habitspark-6ace3.firebaseapp.com',
    storageBucket: 'habitspark-6ace3.firebasestorage.app',
    measurementId: 'G-T9FM61E7D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGvkTmMpsjGzGJyUfnKi5dYFvKUOXefs',
    appId: '1:82887882958:android:0caa94f09a5dcef34d389f',
    messagingSenderId: '82887882958',
    projectId: 'habitspark-6ace3',
    storageBucket: 'habitspark-6ace3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp3vbCpvO7JhdzljvHE3MPfhR0ELUUizM',
    appId: '1:82887882958:ios:8ece1fbcfbf23dd94d389f',
    messagingSenderId: '82887882958',
    projectId: 'habitspark-6ace3',
    storageBucket: 'habitspark-6ace3.firebasestorage.app',
    iosClientId: '82887882958-3rerei6jstb00k2ol8socqakc3bvvav6.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp3vbCpvO7JhdzljvHE3MPfhR0ELUUizM',
    appId: '1:82887882958:ios:8ece1fbcfbf23dd94d389f',
    messagingSenderId: '82887882958',
    projectId: 'habitspark-6ace3',
    storageBucket: 'habitspark-6ace3.firebasestorage.app',
    iosClientId: '82887882958-3rerei6jstb00k2ol8socqakc3bvvav6.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvCpwb9xetODxrgxxVke8JCIZh7lfQU8',
    appId: '1:82887882958:web:0a8a5dc6a23c307f4d389f',
    messagingSenderId: '82887882958',
    projectId: 'habitspark-6ace3',
    authDomain: 'habitspark-6ace3.firebaseapp.com',
    storageBucket: 'habitspark-6ace3.firebasestorage.app',
    measurementId: 'G-0KL4F5QZNS',
  );
}
